[server]
port = 19090
address = "127.0.0.1"
ops_port = 19091
service_name = "HelloService"
degrading = false

[log]
level = "Debug"
path = ""

[[server-client]]
end_point = "127.0.0.1"
service_name = "HelloService"
port = 19090
ops_port = 19091

[[server-client]]
end_point = "192.168.1.3,192.168.1.4"
service_name = "unit_test_service_1"
port = 29090
ops_port = 29091